version: '3.9'
services:
  subdomain:
    container_name: subdomain
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - subdomain-network
    environment:
      - CHOKIDAR_USEPOLLING=true

  caddy:
    image: caddy:alpine
    container_name: caddy-service
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./Caddyfile.dev:/etc/caddy/Caddyfile
      - ./certs:/root/certs
    networks:
      - subdomain-network
    depends_on:
      - subdomain

networks:
  subdomain-network:
    driver: bridge
