FROM node:20.6.1-alpine

WORKDIR /usr/src/app

RUN apk update && apk upgrade
RUN apk add --no-cache sqlite

COPY package.json package-lock.json ./

RUN npm install sqlite3
RUN npm install

COPY . .

EXPOSE 80

CMD ["npm", "run", "dev"]
