version: '3.9'
services:
  subdomain:
    container_name: subdomain
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./Dockerfile.prod
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - subdomain-network

  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - subdomain
    networks:
      - subdomain-network

networks:
  subdomain-network:
    driver: bridge
