version: '3.9'
services:
  subdomain:
    container_name: subdomain
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - subdomain-network
    environment:
      - CHOKIDAR_USEPOLLING=true

networks:
  subdomain-network:
    driver: bridge
