version: '3.9'
services:
  powerlifting:
    container_name: powerlifting
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./Dockerfile.prod
    depends_on:
      - redis
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - powerlifting-network

  redis:
    image: 'redis:7.2.3'
    container_name: redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT}
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    networks:
      - powerlifting-network
    volumes:
      - 'redis-data:/data'

  caddy:
      container_name: caddy
      restart: unless-stopped
      build:
        context: .
        dockerfile: ./Dockerfile
      ports:
        - '80:80'
        - '443:443'
      volumes:
        - ./Caddyfile.prod:/etc/caddy/Caddyfile
      environment:
        - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      networks:
        - powerlifting-network

volumes:
  redis-data:
    driver: local

networks:
  powerlifting-network:
    driver: bridge
