FROM node:22-alpine as build

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .

FROM node:22-alpine

RUN apk update \
    && apk upgrade \
    && apk add --no-cache sqlite curl

# USER node

WORKDIR /usr/src/app

COPY --chown=node:node --from=build /usr/src/app .

EXPOSE 8080

HEALTHCHECK CMD curl -f http://localhost:8080/healthz || exit 1

CMD ["npm", "run", "start"]
