version: '3.9'
services:
  powerlifting:
    container_name: powerlifting
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    depends_on:
      - redis
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - powerlifting-network
    environment:
      - CHOKIDAR_USEPOLLING=true

  redis:
    image: 'redis:7.2.5'
    container_name: redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT}
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    networks:
      - powerlifting-network
    volumes:
      - 'redis-data:/data'

  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander:latest
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - '8081:8081'
    networks:
      - powerlifting-network

  mailhog:
    container_name: mailhot
    restart: unless-stopped
    image: mailhog/mailhog
    ports:
      - '1025:1025'
      - '8025:8025'
    networks:
      - powerlifting-network

volumes:
  redis-data:
    driver: local

networks:
  powerlifting-network:
    driver: bridge
