FROM node:20.6.1-alpine as build

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .

FROM node:20.6.1-alpine

RUN apk update && apk upgrade && apk add curl

# USER node

WORKDIR /usr/src/app

COPY --chown=node:node --from=build /usr/src/app .

EXPOSE 80

HEALTHCHECK CMD curl -f http://localhost:8080/healthz || exit 1

CMD ["npm", "run", "start"]
