services:
  powerlifting:
    container_name: powerlifting
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./Dockerfile.prod
    depends_on:
      - redis
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - powerlifting-network

  redis:
    image: redis:7.2.5
    container_name: redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT} --appendonly yes --replica-read-only no
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    networks:
      - powerlifting-network
    volumes:
      - 'redis-data:/data'

  # caddy:
  #   image: caddy/caddy:2.2.1-alpine
  #   container_name: caddy
  #   restart: unless-stopped
  #   ports:
  #     - '80:80'
  #     - '443:443'
  #   depends_on:
  #     - powerlifting
  #   volumes:
  #     - ./Caddyfile.prod:/etc/caddy/Caddyfile
  #   networks:
  #     - powerlifting-network

  nginx:
    image: nginx:alpine3.18
    container_name: nginx
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - powerlifting
    networks:
      - powerlifting-network

volumes:
  redis-data:
    driver: local

networks:
  powerlifting-network:
    driver: bridge
