export const comments = [
	'Dude, this coach made me feel like I could bench press a truck. Solid gains, bro!',
	"Bro, this coach turned my dad bod into a rad bod. Can't thank him enough!",
	"Yo, this coach's advice is like protein for the mind. Get swole on wisdom!",
	'This coach is the real MVP of motivation. Got me off the couch and onto the grind!',
	"Bro, this coach's pep talks are like pre-workout for your soul. Energizing AF!",
	'Had doubts, but this coach is legit. Turned my setbacks into comebacks!',
	"Never thought I'd say this, but this coach is the GOAT. Total game-changer!",
	"If inspiration had a name, it'd be Coach Bro. Dude's got the playbook to success!",
	"This coach's wisdom hits harder than leg day. No pain, no gain, bro!",
	"Shoutout to Coach Flex for helping me flex my potential. He's the real deal!",
	'Bro, Coach Beastmode unleashed the beast within me. Feel unstoppable now!',
	'Coach Ironman got me feeling like a superhero. Saving the day, one rep at a time!',
	'With Coach Chillax, stress is just a distant memory. Zen vibes all day, bro!',
	"Thanks to Coach Zen Master, I'm as cool as a cucumber under pressure. Namaste, bro!",
	'Coach High Five deserves a high five for turning my frowns upside down. Epic positivity!',
	'Coach Swagger knows how to strut the success walk. Confidence level: through the roof!',
	'Never underestimate the power of Coach Vibes. Positive energy on tap, 24/7!',
	'Coach Firecracker lit up my motivation like the Fourth of July. Explosive results!',
	'Coach Rocksteady keeps me grounded while aiming for the stars. Balance game strong!',
	'Big ups to Coach Zen Warrior for helping me find inner peace through outer strength. Namaste, bro!',
	'Coach Energizer Bunny got me hopping towards my goals. Non-stop motivation!',
	'Coach Dreamweaver turned my aspirations into reality. Living the dream, bro!',
	'With Coach Mind Gym, mental gains are just as important as physical ones. Flexing the brain muscles!',
	'Coach Gamechanger lives up to the name. Game on, bro!',
	'Shoutout to Coach Renaissance Man for helping me become a jack of all trades. Skills unlocked!',
	'Coach Alpha Male taught me to lead the pack. Dominance asserted!',
	'Coach Motivation Station is my one-way ticket to Successville. All aboard!',
	'Coach Legendmaker turned my ordinary story into an epic saga. Living the legend!',
	'With Coach Victory Lap, every day feels like crossing the finish line. Winning streak, engaged!',
	"Coach No Limits showed me there's nothing I can't achieve. Sky's the limit, bro!",
	'Big props to Coach Zen Mastermind for unlocking the secrets of success. Mind over matter, bro!',
	'Coach Phoenix Rising helped me turn setbacks into comebacks. Rising from the ashes, stronger than ever!',
	'Coach Momentum Keeper knows how to keep the ball rolling. Unstoppable force, activated!',
	'With Coach Mojo Maker, good vibes are just a coaching session away. Mojo, boosted!',
	'Coach Dreamcatcher helped me snag my goals like a pro. Sweet dreams, achieved!',
	'Coach Inspiration Nation is where I go for my daily dose of motivation. Feeling inspired, bro!',
	'Coach Dynamo is like a bolt of lightning straight to success. Electrifying results!',
	"Thanks to Coach Power Surge, I'm plugged into success 24/7. Powering up, bro!",
	'Coach Dreamweaver turned my aspirations into reality. Living the dream, bro!',
	'With Coach Mind Gym, mental gains are just as important as physical ones. Flexing the brain muscles!',
	'Coach Gamechanger lives up to the name. Game on, bro!',
	'Shoutout to Coach Renaissance Man for helping me become a jack of all trades. Skills unlocked!',
	'Coach Alpha Male taught me to lead the pack. Dominance asserted!',
	'Coach Motivation Station is my one-way ticket to Successville. All aboard!',
	'Coach Legendmaker turned my ordinary story into an epic saga. Living the legend!',
	'With Coach Victory Lap, every day feels like crossing the finish line. Winning streak, engaged!',
	"Coach No Limits showed me there's nothing I can't achieve. Sky's the limit, bro!",
	'Big props to Coach Zen Mastermind for unlocking the secrets of success. Mind over matter, bro!',
	'Coach Phoenix Rising helped me turn setbacks into comebacks. Rising from the ashes, stronger than ever!',
	'Coach Momentum Keeper knows how to keep the ball rolling. Unstoppable force, activated!',
];
