#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

docker compose exec -T powerlifting npm run format
docker compose exec -T powerlifting npm run lint
docker compose exec -T powerlifting npm run test
