name: CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  format:
    name: Prettier format
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm i

      - name: Format codes
        run: npm run format

  test:
    name: Test
    runs-on: ubuntu-latest

    env:
      DEBUG: true
      PORT: 80
      NODE_ENV: 'testing'
      MY_IP_ADDRESS: '127.0.0.1'
      DEVELOPMENT_APP_URL: 'jaw.lol'
      PRODUCTION_APP_URL: 'app.test'
      SUDO_PASSWORD: 'password'
      SUPER_ADMIN_EMAIL: 'mail@gmail.com'
      PRODUCTION_SSH_URL: 'jaw@127.0.0.1'
      CLOUDFLARE_PURGE_CACHE_API_KEY: 'xxx'
      CLOUDFLARE_POWERLIFTINGDOTGG_ZONE_ID: 'xxx'
      CLOUDFLARE_EMAIL: 'mail@gmail.com'
      SENTRY_DSN: 'xxx'
      GOOGLE_ID: 'xxx'
      GOOGLE_SECRET: 'xxx'
      GOOGLE_REDIRECT_URL: 'xxx'
      SESSION_STORE_PREFIX: 'xxx'
      SESSION_SECRET: 'xxx'
      PRIVATE_BACKBLAZE_BUCKET: 'xxx'
      PRIVATE_BACKBLAZE_REGION: 'xxx'
      PRIVATE_BACKBLAZE_END_POINT: 'xxx'
      PRIVATE_BACKBLAZE_KEY_ID: 'xxx'
      PRIVATE_BACKBLAZE_APPLICATION_KEY: 'xxx'
      PUBLIC_BACKBLAZE_BUCKET: 'xxx'
      PUBLIC_BACKBLAZE_REGION: 'xxx'
      PUBLIC_BACKBLAZE_END_POINT: 'xxx'
      PUBLIC_BACKBLAZE_KEY_ID: 'xxx'
      PUBLIC_BACKBLAZE_APPLICATION_KEY: 'xxx'
      REDIS_HOST: 'redis'
      REDIS_PORT: 6379
      REDIS_PASSWORD: 'password'
      EMAIL_HOST: 'mailhot'
      EMAIL_PORT: 1025
      EMAIL_AUTH_EMAIL: 'name@email.com'
      EMAIL_AUTH_ALIAS: 'mail@jaw.dev'
      EMAIL_AUTH_PASS: 'password'
      DISCORD_ID: 'xxx'
      DISCORD_TOKEN: 'xxx'
      DISCORD_URL: 'xxx'

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm i

      - name: Create SQLite database for Playwright
        run: touch src/database/db.sqlite

      - name: Migrate database for Playwright
        run: npm run db:migrate:latest

      - name: Seed database for Playwright
        run: npm run db:seed:run

      - name: Test codes
        run: npm run test

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Run Playwright tests
        run: npm run test:ete

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  lint:
    name: ESLint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm i

      - name: Lint codes
        run: npm run lint

  # deploy:
  #   needs: [format, lint]
  #   name: Deploy to caprover
  #   runs-on: ubuntu-latest
  #   environment:
  #       name: production
  #       url: https://snap.jaw.dev/

  #   strategy:
  #     matrix:
  #       node-version: [19.x]

  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         cache: 'npm'

  #     - uses: a7ul/tar-action@v1.1.3
  #       with:
  #         command: c
  #         cwd: './'
  #         files: ./
  #         outPath: deploy.tar

  #     - name: Deploy App to CapRover
  #       uses: caprover/deploy-from-github@v1.1.2
  #       with:
  #         server: '${{ secrets.CAPROVER_SERVER }}'
  #         app: '${{ secrets.APP_NAME }}'
  #         token: '${{ secrets.APP_TOKEN }}'
